allow-shorthand: false

# inherits:
  # - strictness_veryhigh

ignore-patterns:
  - (^|\/)\..+
  - ^setup.py$
  - __init__.py$
  - _[vV][0-9.\-_]+[.]py$$|[.]old[.]py$
  
ignore-paths:
  - data
  - font
  - img
  - bak  
  - installer
  - tests
  - toml
  - __init__.py
  - splash.py

pylint-config-file: .pylintrc
# pylint:    
  # disable:
    # - fixme
    # - bad-continuation
    # - trailing-whitespace
    # - missing-final-newline
    # - too-few-public-methods
    # - too-many-public-methods
    # - deprecated-lambda
    # - bad-builtin
    # - star-args
    # - global-statement
    # - assignment-from-none
    # - unused-format-string-key
    # - W5103

  # options:
    # max-locals: 15
    # max-returns: 6
    # max-branches: 15
    # max-statements: 60
    # min-public-methods: 1
    # max-public-methods: 20
    # max-module-lines: 1000
    # max-line-length: 99

pep8:
  options:
    max-line-length: 99
    single-line-if-stmt: n
  disable:
    - E304
    - E265
    - E266
    - W291
    - W292
    - W391
    - N811
    - N812
    - N813
    - N814
    
pyflakes:
  disable:
    - F403
    - F810

frosted:
  disable:
    - E103
    - E306
    
pyroma:
  disable:
    - PYR15
    - PYR16
    - PYR17
    - PYR18
    - PYR19
    
mccabe:
  options:
    max-complexity: 15

pep257:
  disable:
    - D000
    - D400
    - D401