inherits:
    - strictness_high

ignore-patterns:
    - (^|\/|\\)\..+
    - (^|\/|\\)setup.py$
    - .*(^|\/|\\)splash.py$       #imported many modules in splash, but not used
    # - (^|\/|\\)__init__.py$     #reimported modules in __init__, but not used
    - .*(_[vV][0-9.\-_]+[.]py$$|[.]old[.]py$$|_bak[.]py$)  #old version scripts
    - .*(^|\/|\\)bak(\/|\\|$).*   #old version scripts
    - .*(^|\/|\\)toml(\/|\\|$).*  #3rdparty scripts
  
ignore-paths:
    - /res
    - /installer     #scripts for installer binary
    - /tests         #tests scripts

# uses: uses must be name of django, celery, flask

# default tools: profile-validator pep8 pyflakes mccabe dodgy
# without tools: pylint pydocstyle

#pylint-config-file: .pylintrc
pylint: # run pylint in prospector will cause an error
    run: false

pep8:
    options:
        max-line-length: 99
        single-line-if-stmt: n
    disable:
        - E304
        - E265
        - E266
        - W291
        - W292
        - W391
        - N811
        - N812
        - N813
        - N814
        - N802
        - N803
        - N806
    
pyflakes:
    disable:
        - F403
        - F810

frosted:
    disable:
        - E103
        - E306
    
pyroma:
    disable:
        - PYR15
        - PYR16
        - PYR17
        - PYR18
        - PYR19
    
mccabe:
    options:
        max-complexity: 15

pep257:
    disable:
        - D000
        - D400
        - D401