#sudo: true
language: python
virtualenv:
  system_site_packages: true

jobs:
    include:
        - name: "win"
          os: windows
          python:
            - "3.7"
            - "3.6"
            - "3.5"
        - name: "linux"
          os: linux
          python: 3.7
        - name: "macOS"
          os: osx
          #osx_image: xcode11
          python: 3.7
          
#before_install: pip3 install --upgrade pip

install:
    - pip install PyQt5
    - pip install QsciScintilla
    
script:
    - app.py