language: python # this works for Linux but is an error on macOS or Windows

jobs:
    include:
        - name: "linux" 
          os: linux
          sudo: required
          dist: bionic
          python:
            - 3.7
          before_install:
            - sudo apt-get -qq update
            - sudo apt-get -y -qq install python3
            - python --version
            - pip3 install -U pip
            - pip3 install chardet # can't import chardet from .zip
            
        - name: "win"
          os: windows           # Windows 10.0.17134 N/A Build 17134
          language: shell       # 'language: python' is an error on Travis CI Windows
          before_install:
            - choco install python3 #--version 3.7.4 3.8.0
            - python -m pip install --upgrade pip
            - pip3 install chardet # can't import chardet from .zip
          env:
            - PATH=/c/Python38:/c/Python38/Scripts:$PATH
            
        - name: "macOS"
          os: osx
          osx_image: xcode11 #python3.7
          #xcode10.2 with py3.7.3 xcode9.4 with py3.6.5 xcode9.3 with py2.7.14_2
          language: shell # 'language: python' is an error on Travis CI macOS
          
before_install: 
    - python3 --version
    - pip3 install -U pip

install:
    - pip3 install PyQt5
    - pip3 install Qscintilla
    - pip3 install -U pytest
    - pip3 install -U pytest-qt
    
script: pytest || python3 -m pytest    # pytest command won't be found on osx
    # 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
    # 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
    #- python3 app.py || py app.py
    