#sudo: true
language: python
# virtualenv:
  # system_site_packages: true

jobs:
    include:
        - name: "linux"
          os: linux
          python:
            - 3.7
            - 3.6
            - 3.5
        - name: "win"
          os: windows           # Windows 10.0.17134 N/A Build 17134
          language: shell       # 'language: python' is an error on Travis CI Windows
          before_install:
            - choco install python --version 3.7.4
            - python -m pip install --upgrade pip
          env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - name: "macOS"
          os: osx
          osx_image: xcode11 #python 3.7
          language: shell # 'language: python' is an error on Travis CI macOS
          
before_install: pip install --upgrade pip

install:
    - pip3 install PyQt5
    - pip3 install Qscintilla
    
script:
    - python3 app.py