#sudo: true
language: python # this works for Linux but is an error on macOS or Windows

env:
    - TRAVIS-CI_TESTING=1 # app正常退出

jobs:
    include:
        - name: "linux"
          os: linux
          python:
            - 3.7
            - 3.6
            - 3.5
          sudo: true
          before_install:
            - sudo apt-get install libx11-dev libxext-dev libxtst-dev
            - sudo apt-get install xlibmesa-gl-dev libglu1-mesa-dev
        - name: "win"
          os: windows           # Windows 10.0.17134 N/A Build 17134
          language: shell       # 'language: python' is an error on Travis CI Windows
          before_install:
            - choco install python --version 3.7.4
            - python -m pip install --upgrade pip
          env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - name: "macOS"
          os: osx
          osx_image: xcode11 #python 3.7
          language: shell # 'language: python' is an error on Travis CI macOS
          
before_install: pip install --upgrade pip

install:
    - pip3 install PyQt5
    - pip3 install Qscintilla
    
script:
    # 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
    # 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
    - python3 app.py || py app.py