[file]
recent = [ "C:\\Users\\lei\\AppData\\Local\\Temp\\pytest-of-lei\\pytest-181\\test_fileop_and_clrpic0\\new.qsst", "C:\\Users\\lei\\AppData\\Local\\Temp\\pytest-of-lei\\pytest-180\\test_fileop_and_clrpic0\\new.qsst", "C:\\Users\\lei\\AppData\\Local\\Temp\\pytest-of-lei\\pytest-179\\test_fileop_and_clrpic0\\new.qsst", "C:\\Users\\lei\\AppData\\Local\\Temp\\pytest-of-lei\\pytest-178\\test_fileop_and_clrpic0\\new.qsst", "C:\\Users\\lei\\AppData\\Local\\Temp\\pytest-of-lei\\pytest-177\\test_fileop_and_clrpic0\\new.qsst", "C:\\Users\\lei\\AppData\\Local\\Temp\\pytest-of-lei\\pytest-176\\test_fileop_and_clrpic0\\new.qsst", "C:\\Users\\lei\\AppData\\Local\\Temp\\pytest-of-lei\\pytest-175\\test_fileop_and_clrpic0\\new.qsst", "C:\\Users\\lei\\AppData\\Local\\Temp\\pytest-of-lei\\pytest-174\\test_fileop_and_clrpic0\\new.qsst",]
recentcount = 8

[editor]
fontsize = 11

[general]
language = ""
