[file]
recent = [ "C:\\Users\\lei\\AppData\\Local\\Temp\\pytest-of-lei\\pytest-20\\test_file0\\new.qsst", "C:\\Users\\lei\\AppData\\Local\\Temp\\pytest-of-lei\\pytest-19\\test_file0\\new.qsst", "C:\\Users\\lei\\AppData\\Local\\Temp\\pytest-of-lei\\pytest-18\\test_file0\\new.qsst", "data/default.qss",]
recentcount = 8

[editor]
fontsize = 11

[general]
language = ""
