[general]
language = ""

[file]
recent = [ "C:\\Users\\lei\\AppData\\Local\\Temp\\pytest-of-lei\\pytest-397\\test_fileop_and_clrpic0\\new.qsst", "C:\\Users\\lei\\AppData\\Local\\Temp\\pytest-of-lei\\pytest-396\\test_fileop_and_clrpic0\\new.qsst", "C:\\Users\\lei\\AppData\\Local\\Temp\\pytest-of-lei\\pytest-395\\test_fileop_and_clrpic0\\new.qsst", "C:\\Users\\lei\\AppData\\Local\\Temp\\pytest-of-lei\\pytest-394\\test_fileop_and_clrpic0\\new.qsst",]
recentcount = 4

[CodeEditor]
fontsize = 11
