[file]
recent = [ "C:/Users/Public/Desktop/Radialix 3 64 位.lnk", "C:/Users/lei/Desktop/Img2CAD.lnk", "C:/Users/Public/Desktop/STAR-CCM+ 12.02.010-R8 用于 Windows 64.lnk", "C:/Users/lei/Desktop/Swift for Windows.lnk", "E:/Working/Coding/Python/QssStylesheetEditor/data/default.qss",]
recentcount = 8

[editor]
fontsize = 11

[general]
language = "zh-CN"
